name: CI

on: [pull_request]

jobs:
  build:
    name: Build and test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        node-version:
          - 12
          - 14
          - 16

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node ${{ runner.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ runner.node-version }}

      - uses: actions/cache@v2
        with:
          path: ~/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: npm install --prefer-offline

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run ts

      - name: Test
        run: npm run test

      - name: Generate code coverage
        if: success() && github.ref == 'refs/heads/main' && ${{ runner.os }} == 'ubuntu-latest' && 16 == ${{ runner.node-version }}
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: b4ef7769e0f8f04456e8e1168b4beb44561bd5ce9ca216458a164e19c4cf7308
        with:
          coverageCommand: npm run coverage
          debug: true

      - name: Semantic Release
        if: success() && github.ref == 'refs/heads/main' && ${{ runner.os }} == 'ubuntu-latest' && 16 == ${{ runner.node-version }}
        uses: cycjimmy/semantic-release-action@v2
        with:
          branches: "main"
          extra_plugins: |
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
